version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/BungieSharper"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/BungieSharper.Generator"
    schedule:
      interval: "daily"
