version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/BungieSharp"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/BungieSharp.Generator"
    schedule:
      interval: "daily"
