using BungieSharper.Entities;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BungieSharper.Endpoints;

[JsonSerializable(typeof(ApiResponse<Entities.Applications.ApiUsage>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.Applications.Application>>))]
[JsonSerializable(typeof(ApiResponse<Entities.User.GeneralUser>))]
[JsonSerializable(typeof(ApiResponse<Dictionary<byte, string>>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.User.Models.GetCredentialTypesForAccountResponse>>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.Config.UserTheme>>))]
[JsonSerializable(typeof(ApiResponse<Entities.User.UserMembershipData>))]
[JsonSerializable(typeof(ApiResponse<Entities.User.HardLinkedUserMembership>))]
[JsonSerializable(typeof(ApiResponse<Entities.User.UserSearchResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Content.Models.ContentTypeDescription>))]
[JsonSerializable(typeof(ApiResponse<Entities.Content.ContentItemPublicContract>))]
[JsonSerializable(typeof(ApiResponse<Entities.SearchResultOfContentItemPublicContract>))]
[JsonSerializable(typeof(ApiResponse<object>))]
[JsonSerializable(typeof(ApiResponse<Entities.Content.NewsArticleRssResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Forum.PostSearchResponse>))]
[JsonSerializable(typeof(ApiResponse<long>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.Tags.Models.Contracts.TagResponse>>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.Forum.ForumRecruitmentDetail>>))]
[JsonSerializable(typeof(ApiResponse<Dictionary<int, string>>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.Config.GroupTheme>>))]
[JsonSerializable(typeof(ApiResponse<bool>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.GroupsV2.GroupV2Card>>))]
[JsonSerializable(typeof(ApiResponse<Entities.GroupsV2.GroupSearchResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.GroupsV2.GroupResponse>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.GroupsV2.GroupOptionalConversation>>))]
[JsonSerializable(typeof(ApiResponse<int>))]
[JsonSerializable(typeof(ApiResponse<Entities.SearchResultOfGroupMember>))]
[JsonSerializable(typeof(ApiResponse<Entities.GroupsV2.GroupMemberLeaveResult>))]
[JsonSerializable(typeof(ApiResponse<Entities.SearchResultOfGroupBan>))]
[JsonSerializable(typeof(ApiResponse<Entities.SearchResultOfGroupMemberApplication>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.Entities.EntityActionResult>>))]
[JsonSerializable(typeof(ApiResponse<Entities.GroupsV2.GetGroupsForMemberResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.GroupsV2.GroupMembershipSearchResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.GroupsV2.GroupPotentialMembershipSearchResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.GroupsV2.GroupApplicationResponse>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.Tokens.PartnerOfferSkuHistoryResponse>>))]
[JsonSerializable(typeof(ApiResponse<Entities.Tokens.PartnerRewardHistoryResponse>))]
[JsonSerializable(typeof(ApiResponse<Dictionary<string, Entities.Tokens.BungieRewardDisplay>>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Config.DestinyManifest>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Definitions.DestinyDefinition>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.User.UserInfoCard>>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Responses.DestinyLinkedProfilesResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Responses.DestinyProfileResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Responses.DestinyCharacterResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Milestones.DestinyMilestone>))]
[JsonSerializable(typeof(ApiResponse<Entities.Config.ClanBanner.ClanBannerSource>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Responses.DestinyItemResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Responses.DestinyVendorsResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Responses.DestinyVendorResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Responses.DestinyPublicVendorsResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Responses.DestinyCollectibleNodeDetailResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.DestinyEquipItemResults>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Responses.DestinyItemChangeResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.HistoricalStats.DestinyPostGameCarnageReportData>))]
[JsonSerializable(typeof(ApiResponse<Dictionary<string, Entities.Destiny.HistoricalStats.Definitions.DestinyHistoricalStatsDefinition>>))]
[JsonSerializable(typeof(ApiResponse<Dictionary<string, Dictionary<string, Entities.Destiny.HistoricalStats.DestinyLeaderboard>>>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.Destiny.HistoricalStats.DestinyClanAggregateStat>>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Definitions.DestinyEntitySearchResult>))]
[JsonSerializable(typeof(ApiResponse<Dictionary<string, Entities.Destiny.HistoricalStats.DestinyHistoricalStatsByPeriod>>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.HistoricalStats.DestinyHistoricalStatsAccountResult>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.HistoricalStats.DestinyActivityHistoryResults>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.HistoricalStats.DestinyHistoricalWeaponStatsData>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.HistoricalStats.DestinyAggregateActivityResults>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Milestones.DestinyMilestoneContent>))]
[JsonSerializable(typeof(ApiResponse<Dictionary<uint, Entities.Destiny.Milestones.DestinyPublicMilestone>>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Advanced.AwaInitializeResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Destiny.Advanced.AwaAuthorizationResult>))]
[JsonSerializable(typeof(ApiResponse<Entities.Trending.TrendingCategories>))]
[JsonSerializable(typeof(ApiResponse<Entities.SearchResultOfTrendingEntry>))]
[JsonSerializable(typeof(ApiResponse<Entities.Trending.TrendingDetail>))]
[JsonSerializable(typeof(ApiResponse<Entities.SearchResultOfFireteamSummary>))]
[JsonSerializable(typeof(ApiResponse<Entities.SearchResultOfFireteamResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Fireteam.FireteamResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Social.Friends.BungieFriendListResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Social.Friends.BungieFriendRequestListResponse>))]
[JsonSerializable(typeof(ApiResponse<Entities.Social.Friends.PlatformFriendResponse>))]
[JsonSerializable(typeof(ApiResponse<Dictionary<string, string>>))]
[JsonSerializable(typeof(ApiResponse<Entities.Common.Models.CoreSettingsConfiguration>))]
[JsonSerializable(typeof(ApiResponse<Dictionary<string, Entities.Common.Models.CoreSystem>>))]
[JsonSerializable(typeof(ApiResponse<IEnumerable<Entities.GlobalAlert>>))]
[JsonSerializable(typeof(Entities.User.UserSearchPrefixRequest))]
[JsonSerializable(typeof(IEnumerable<long>))]
[JsonSerializable(typeof(Entities.GroupsV2.GroupQuery))]
[JsonSerializable(typeof(Entities.GroupsV2.GroupNameSearchRequest))]
[JsonSerializable(typeof(Entities.GroupsV2.GroupEditAction))]
[JsonSerializable(typeof(Entities.GroupsV2.ClanBanner))]
[JsonSerializable(typeof(Entities.GroupsV2.GroupOptionsEditAction))]
[JsonSerializable(typeof(Entities.GroupsV2.GroupOptionalConversationAddRequest))]
[JsonSerializable(typeof(Entities.GroupsV2.GroupOptionalConversationEditRequest))]
[JsonSerializable(typeof(Entities.GroupsV2.GroupBanRequest))]
[JsonSerializable(typeof(Entities.GroupsV2.GroupApplicationRequest))]
[JsonSerializable(typeof(Entities.GroupsV2.GroupApplicationListRequest))]
[JsonSerializable(typeof(Entities.Tokens.PartnerOfferClaimRequest))]
[JsonSerializable(typeof(Entities.User.ExactSearchRequest))]
[JsonSerializable(typeof(Entities.Destiny.Requests.DestinyItemTransferRequest))]
[JsonSerializable(typeof(Entities.Destiny.Requests.Actions.DestinyPostmasterTransferRequest))]
[JsonSerializable(typeof(Entities.Destiny.Requests.Actions.DestinyItemActionRequest))]
[JsonSerializable(typeof(Entities.Destiny.Requests.Actions.DestinyItemSetActionRequest))]
[JsonSerializable(typeof(Entities.Destiny.Requests.Actions.DestinyLoadoutActionRequest))]
[JsonSerializable(typeof(Entities.Destiny.Requests.Actions.DestinyLoadoutUpdateActionRequest))]
[JsonSerializable(typeof(Entities.Destiny.Requests.Actions.DestinyItemStateRequest))]
[JsonSerializable(typeof(Entities.Destiny.Requests.Actions.DestinyInsertPlugsActionRequest))]
[JsonSerializable(typeof(Entities.Destiny.Requests.Actions.DestinyInsertPlugsFreeActionRequest))]
[JsonSerializable(typeof(Entities.Destiny.Reporting.Requests.DestinyReportOffensePgcrRequest))]
[JsonSerializable(typeof(Entities.Destiny.Advanced.AwaPermissionRequested))]
[JsonSerializable(typeof(Entities.Destiny.Advanced.AwaUserResponse))]
[JsonSerializable(typeof(ApiResponse))]
[JsonSerializable(typeof(TokenResponse))]
internal partial class BungieSharperDeserializeJsonContext : JsonSerializerContext { }