name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      TEST_BUNGIE_API_KEY: ${{ secrets.TEST_BUNGIE_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build generator
      run: dotnet build BungieSharper.Generator --configuration Release
    - name: Run generator
      run: dotnet run --project BungieSharper.Generator --no-restore --verbosity normal
    - name: Build client
      run: dotnet build BungieSharper --configuration Release
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.ref }} - ${{ github.sha }} 
        path: 'BungieSharper/bin/Release/netcoreapp3.1/'
    - name: Build test
      run: dotnet build BungieSharper.Tests --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal  --configuration Release
