name: Main pull request/push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      TEST_BUNGIE_API_KEY: ${{ secrets.TEST_BUNGIE_API_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get short SHA
      uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 8

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        include-prerelease: false

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build client
      run: dotnet build ./BungieSharper -c Release

    - name: Pack entities NuGet package
      run: dotnet pack ./BungieSharper.Entities -c Release --no-build --output OutputPackage --version-suffix "ci.$(date -u +%Y%m%dT%H%M%S)+sha.${GITHUB_SHA:0:9}" -p:ContinuousIntegrationBuild=true

    - name: Pack client NuGet package
      run: dotnet pack ./BungieSharper -c Release --no-build --output OutputPackage --version-suffix "ci.$(date -u +%Y%m%dT%H%M%S)+sha.${GITHUB_SHA:0:9}" -p:ContinuousIntegrationBuild=true

    - name: Upload artifact (nupkg/snupkg)
      uses: actions/upload-artifact@v1
      with:
        name: BungieSharper - ${{ env.SHA }}
        path: OutputPackage

    - name: Build test
      run: dotnet build ./BungieSharper.Tests -c Release

    - name: Run test
      run: dotnet test ./BungieSharper.Tests -c Release --no-build --verbosity normal