name: main PR+push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      TEST_BUNGIE_API_KEY: ${{ secrets.TEST_BUNGIE_API_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Get version suffix
      id: get_suffix
      run: echo ::set-output name=SUFFIX::${GITHUB_SHA:0:9}

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false

    - name: Pack entities NuGet package
      run: dotnet pack ./BungieSharper.Entities -c Release --output OutputPackage -p:ContinuousIntegrationBuild=true -p:VersionSuffix=${{ steps.get_suffix.outputs.SUFFIX }}

    - name: Pack client NuGet package
      run: dotnet pack ./BungieSharper -c Release --output OutputPackage -p:ContinuousIntegrationBuild=true -p:VersionSuffix=${{ steps.get_suffix.outputs.SUFFIX }}

    - name: Upload artifact (nupkg/snupkg)
      uses: actions/upload-artifact@v1
      with:
        name: BungieSharper_${{ steps.get_suffix.outputs.SUFFIX }}
        path: OutputPackage

    - name: Run test
      run: dotnet test ./BungieSharper.Tests -c Release --verbosity normal