name: Main pull request/push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      dotnet_sdk_version: '5.0.102'
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      TEST_BUNGIE_API_KEY: ${{ secrets.TEST_BUNGIE_API_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get short SHA
      uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 8

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_sdk_version }}

    - name: Build client
      run: dotnet build ./BungieSharper -c Release

    - name: Pack schema NuGet package
      run: dotnet pack ./BungieSharper.Schema -c Release --no-build --output SchemaPackage --version-suffix "ci.$(date -u +%Y%m%dT%H%M%S)+sha.${GITHUB_SHA:0:9}" -p:ContinuousIntegrationBuild=true

    - name: Pack client NuGet package
      run: dotnet pack ./BungieSharper -c Release --no-build --output ClientPackage --version-suffix "ci.$(date -u +%Y%m%dT%H%M%S)+sha.${GITHUB_SHA:0:9}" -p:ContinuousIntegrationBuild=true

    - name: Upload schema artifact (nupkg/snupkg)
      uses: actions/upload-artifact@v1
      with:
        name: BungieSharper.Schema - ${{ env.SHA }}
        path: SchemaPackage

    - name: Upload client artifact (nupkg/snupkg)
      uses: actions/upload-artifact@v1
      with:
        name: BungieSharper - ${{ env.SHA }}
        path: ClientPackage

    - name: Build test
      run: dotnet build ./BungieSharper.Tests -c Release

    - name: Run test
      run: dotnet test ./BungieSharper.Tests -c Release --no-build --verbosity normal